name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    name: DeploySubgraph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Bump version and push tag
        id: tag_version
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "name=dir::$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy to Holesky
        env:
          VERSION_TAG: ${{ steps.tag_version.outputs.new_tag }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: export DEPLOY_KEY=${{ env.ACCESS_TOKEN }} && export VERSION_TAG=${{ env.VERSION_TAG }} && yarn deploy:holesky
